prompt ________________________________________________
prompt 
prompt Installing Scanworks Core Triggers
prompt ________________________________________________

prompt ------------------------------------------------

prompt Creating Scanworks Transaction System Triggers

prompt ------------------------------------------------

prompt Creating Transactions Triggers

CREATE OR REPLACE TRIGGER ESI_SW_TRANSACTIONS_UTR
  BEFORE UPDATE ON ESI_SW_TRANSACTIONS_TAB
    FOR EACH ROW
BEGIN

    UPDATE ESI_SW_FIELDS_TAB FIELDS
       SET FIELDS.TRANSACTION = :NEW.TRANSACTION
     WHERE FIELDS.TRANSACTION = :OLD.TRANSACTION;
     
    UPDATE ESI_SW_MENU_ITEMS_TAB ITEMS
       SET ITEMS.TRANSACTION = :NEW.TRANSACTION
     WHERE ITEMS.TRANSACTION = :OLD.TRANSACTION;

    UPDATE ESI_SW_LABELS_TAB LABELS
       SET LABELS.TRANSACTION = :NEW.TRANSACTION
     WHERE LABELS.TRANSACTION = :OLD.TRANSACTION;
      
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END ESI_SW_TRANSACTIONS_TAB;
/

prompt ------------------------------------------------

prompt Creating Scanworks Printing System Triggers

prompt ------------------------------------------------

prompt Creating Label Print Sites Triggers

CREATE OR REPLACE TRIGGER ESI_SW_PRINT_SITES_UTR
AFTER UPDATE
ON ESI_SW_PRINT_SITES_TAB 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN

    UPDATE ESI_SW_PRINTERS_TAB PR 
    SET PR.CONTRACT = :NEW.CONTRACT
    WHERE PR.CONTRACT = :OLD.CONTRACT;

    UPDATE ESI_SW_LABEL_NAMES_TAB PR 
    SET PR.CONTRACT = :NEW.CONTRACT
    WHERE PR.CONTRACT = :OLD.CONTRACT;
   
   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ESI_SW_PRINT_SITES_UTR;
/

prompt Creating Label Printers Triggers

CREATE OR REPLACE TRIGGER ESI_SW_PRINTERS_UTR
  AFTER UPDATE ON ESI_SW_PRINTERS_TAB
    FOR EACH ROW
BEGIN

     IF (:OLD.CONTRACT <> :NEW.CONTRACT)  THEN
        UPDATE ESI_SW_MENU_ITEMS_TAB ITEMS
            SET ITEMS.PRINTER_NO = NULL,
                ITEMS.PRINTER_CONTRACT = NULL
        WHERE ITEMS.PRINTER_NO = :OLD.PRINTER_NO
        AND ITEMS.PRINTER_CONTRACT = :OLD.CONTRACT
        AND ITEMS.CONTRACT = :OLD.CONTRACT;
    ELSE
        UPDATE ESI_SW_MENU_ITEMS_TAB ITEMS
            SET ITEMS.PRINTER_NO = :NEW.PRINTER_NO
        WHERE ITEMS.PRINTER_NO = :OLD.PRINTER_NO
        AND ITEMS.PRINTER_CONTRACT = :OLD.CONTRACT
        AND ITEMS.CONTRACT = :OLD.CONTRACT;
   END IF;


EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END ESI_SW_MENUS_UTR;
/

prompt Creating Label Names Triggers

CREATE OR REPLACE TRIGGER ESI_SW_LABEL_NAMES_UTR
AFTER UPDATE
ON ESI_SW_LABEL_NAMES_TAB 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE

BEGIN

    IF (:OLD.CONTRACT <> :NEW.CONTRACT) THEN
     DELETE FROM ESI_SW_LABELS_TAB LABELS
     WHERE LABELS.LABEL_NAME = :OLD.LABEL_NAME
       AND LABELS.CONTRACT = :OLD.CONTRACT;
    ELSE
     UPDATE ESI_SW_LABELS_TAB LABELS
       SET LABELS.LABEL_NAME = :NEW.LABEL_NAME
     WHERE LABELS.LABEL_NAME = :OLD.LABEL_NAME
       AND LABELS.CONTRACT = :OLD.CONTRACT;
    END IF;   
END ESI_SW_LABEL_NAMES_UTR;
/

prompt ------------------------------------------------

prompt Creating Scanworks Menu System Triggers

prompt ------------------------------------------------

prompt Creating Menus Triggers

CREATE OR REPLACE TRIGGER ESI_SW_MENUS_UTR
  BEFORE UPDATE ON ESI_SW_MENUS_TAB
    FOR EACH ROW
BEGIN
    UPDATE ESI_SW_MENU_ITEMS_TAB ITEMS
       SET ITEMS.CONTRACT = :NEW.CONTRACT,
           ITEMS.MENU_NAME = :NEW.MENU_NAME
     WHERE ITEMS.CONTRACT = :OLD.CONTRACT
       AND ITEMS.MENU_NAME = :OLD.MENU_NAME;
           
    UPDATE ESI_SW_MENU_ITEMS_TAB ITEMS
       SET ITEMS.PRINTER_CONTRACT = '*',
           ITEMS.PRINTER_NO = '*'
     WHERE ITEMS.CONTRACT = :OLD.CONTRACT
       AND ITEMS.MENU_NAME = :OLD.MENU_NAME
       AND ITEMS.PRINTER_CONTRACT = :OLD.CONTRACT
       AND ITEMS.PRINTER_CONTRACT = :NEW.CONTRACT;
           
    UPDATE ESI_SW_MENU_ITEMS_TAB ITEMS
       SET ITEMS.SUBMENU = :NEW.MENU_NAME
     WHERE ITEMS.CONTRACT = :OLD.CONTRACT
       AND ITEMS.SUBMENU = :OLD.MENU_NAME
       AND ITEMS.SUBMENU_CONTRACT = :OLD.CONTRACT
       AND ITEMS.SUBMENU_CONTRACT = :NEW.CONTRACT;
    
    DELETE FROM ESI_SW_MENU_ITEMS_TAB ITEMS
     WHERE ITEMS.CONTRACT = :OLD.CONTRACT
       AND ITEMS.SUBMENU = :OLD.MENU_NAME
       AND ITEMS.SUBMENU_CONTRACT = :OLD.CONTRACT
       AND ITEMS.SUBMENU_CONTRACT != :NEW.CONTRACT;
    
    UPDATE ESI_SW_USERS_TAB USERS
       SET USERS.CONTRACT = :NEW.CONTRACT,
           USERS.MENU_NAME = :NEW.MENU_NAME
     WHERE USERS.CONTRACT = :OLD.CONTRACT
       AND USERS.MENU_NAME = :OLD.MENU_NAME
       AND USERS.CONTRACT = :NEW.CONTRACT;
       
    UPDATE ESI_SW_USERS_TAB USERS
       SET USERS.CONTRACT = '*',
           USERS.MENU_NAME = '*'
     WHERE USERS.CONTRACT = :OLD.CONTRACT
       AND USERS.MENU_NAME = :OLD.MENU_NAME
       AND USERS.CONTRACT != :NEW.CONTRACT;
       
EXCEPTION 
  WHEN OTHERS THEN
    RAISE;
END ESI_SW_MENUS_UTR;
/
  
prompt Creating Menu Icons Triggers