prompt ________________________________________________
prompt 
prompt Installing Scanworks Core Table Keys
prompt ________________________________________________

prompt ------------------------------------------------

prompt Creating Scanworks Transaction System Table Keys

prompt ------------------------------------------------

prompt Creating Transactions Table Keys
ALTER TABLE ESI_SW_TRANSACTIONS_TAB
  ADD CONSTRAINT SW_TRANSACTIONS_PK 	PRIMARY KEY (TRANSACTION);

prompt Creating Transaction Fields Table Keys
ALTER TABLE ESI_SW_FIELDS_TAB
  ADD 	CONSTRAINT 		SW_FIELDS_PK 				PRIMARY KEY (TRANSACTION, FIELD_ID)
  ADD 	CONSTRAINT 		SW_FIELDS_FK1 				FOREIGN KEY (TRANSACTION)
		REFERENCES 		ESI_SW_TRANSACTIONS_TAB 				(TRANSACTION)
		ON DELETE 		CASCADE;
	
prompt Creating Transaction History Table Keys
ALTER TABLE ESI_SW_TRANSACTION_LOG_TAB
  ADD 	CONSTRAINT 		SW_TRANSACTION_LOG_PK 		PRIMARY KEY (TRANSACTION_ID);

prompt ------------------------------------------------

prompt Creating Scanworks Printing System Table Keys

prompt ------------------------------------------------

prompt Creating Label Print Sites Table Keys
ALTER TABLE ESI_SW_PRINT_SITES_TAB
  ADD 	CONSTRAINT 		SW_PRINT_SITES_PK 			PRIMARY KEY (CONTRACT);

prompt Creating Label Printers Table Keys
ALTER TABLE ESI_SW_PRINTERS_TAB
  ADD 	CONSTRAINT 		SW_PRINTERS_PK 				PRIMARY KEY (CONTRACT, PRINTER_NO)
  ADD 	CONSTRAINT 		SW_PRINTERS_FK1 			FOREIGN KEY (CONTRACT)
		REFERENCES 		ESI_SW_PRINT_SITES_TAB 					(CONTRACT)
		ON DELETE 		CASCADE;

prompt Creating Label Names Table Keys
ALTER TABLE ESI_SW_LABEL_NAMES_TAB
  ADD 	CONSTRAINT 		SW_LABEL_NAMES_PK 			PRIMARY KEY (CONTRACT, LABEL_NAME)
  ADD 	CONSTRAINT 		SW_LABEL_NAMES_FK1 			FOREIGN KEY (CONTRACT)
		REFERENCES 		ESI_SW_PRINT_SITES_TAB 					(CONTRACT)
		ON DELETE 		CASCADE;

prompt Creating Labels Table Keys
ALTER TABLE ESI_SW_LABELS_TAB
  ADD 	CONSTRAINT 		SW_LABELS_PK 				PRIMARY KEY (CONTRACT, TRANSACTION, PART_NO, PART_MAIN_GROUP)
  ADD 	CONSTRAINT 		SW_LABELS_FK1 				FOREIGN KEY (CONTRACT, LABEL_NAME)
		REFERENCES 		ESI_SW_LABEL_NAMES_TAB 					(CONTRACT, LABEL_NAME)
		ON DELETE 		CASCADE
  ADD 	CONSTRAINT 		SW_LABELS_FK2 				FOREIGN KEY (TRANSACTION)
		REFERENCES 		ESI_SW_TRANSACTIONS_TAB 				(TRANSACTION)
		ON DELETE 		CASCADE;		

prompt ------------------------------------------------

prompt Creating Scanworks Menu System Tables Keys

prompt ------------------------------------------------

prompt Creating Menus Table Keys
ALTER TABLE ESI_SW_MENUS_TAB
  ADD 	CONSTRAINT 		SW_MENUS_PK 				PRIMARY KEY (CONTRACT, MENU_NAME);
  
prompt Menu Icons Table Keys
ALTER TABLE ESI_SW_ICONS_TAB
  ADD 	CONSTRAINT 		SW_ICONS_PK 				PRIMARY KEY (ICON);

prompt Creating Users Table Keys
ALTER TABLE ESI_SW_USERS_TAB
  ADD 	CONSTRAINT 		SW_USERS_PK 				PRIMARY KEY (IDENTITY)
  ADD 	CONSTRAINT 		SW_USERS_FK1 				FOREIGN KEY (CONTRACT, MENU_NAME)
		REFERENCES 		ESI_SW_MENUS_TAB 						(CONTRACT, MENU_NAME)
		ON DELETE 		SET NULL;

prompt Creating Menu Items Table Keys
ALTER TABLE ESI_SW_MENU_ITEMS_TAB
  ADD 	CONSTRAINT 		SW_MENU_ITEMS_PK 			PRIMARY KEY (CONTRACT, MENU_NAME, TRANSACTION, SUBMENU)
  ADD 	CONSTRAINT 		SW_MENU_ITEMS_FK1 			FOREIGN KEY (CONTRACT, MENU_NAME)
		REFERENCES 		ESI_SW_MENUS_TAB 						(CONTRACT, MENU_NAME)
		ON DELETE 		CASCADE
  ADD 	CONSTRAINT 		SW_MENU_ITEMS_FK2 			FOREIGN KEY (TRANSACTION)
		REFERENCES 		ESI_SW_TRANSACTIONS_TAB					(TRANSACTION)
		ON DELETE 		CASCADE
  ADD 	CONSTRAINT 		SW_MENU_ITEMS_FK3 			FOREIGN KEY (SUBMENU_CONTRACT, SUBMENU)
		REFERENCES 		ESI_SW_MENUS_TAB 						(CONTRACT, MENU_NAME)
		ON DELETE 		CASCADE  
  ADD 	CONSTRAINT 		SW_MENU_ITEMS_FK4 			FOREIGN KEY (ICON)
		REFERENCES 		ESI_SW_ICONS_TAB 						(ICON)
		ON DELETE 		SET NULL
  ADD 	CONSTRAINT 		SW_MENU_ITEMS_FK5 			FOREIGN KEY (PRINTER_CONTRACT, PRINTER_NO)
		REFERENCES 		ESI_SW_PRINTERS_TAB 					(CONTRACT, PRINTER_NO)
		ON DELETE 		SET NULL; 