LOAD DATA 
INFILE 'icons.csv'
--INTO TABLE ESI_aa_ICONS_TAB
INTO TABLE ESI_SW_ICONS_TAB
FIELDS TERMINATED BY ','
(ICON              CHAR(100),
 ICON_FILENAME     FILLER CHAR(2000),
 ICON_FILE         LOBFILE(ICON_FILENAME) TERMINATED BY EOF)