CREATE OR REPLACE VIEW ESI_MAINT_MATERIAL_REQUIS_LINE AS
SELECT  mmr.maint_material_order_no        maint_material_order_no,                                        
  	mmr.signature_id                   signature_id,                                                   
  	mmr.int_destination_id             int_destination_id,                                             
  	mmr.due_date                       due_date,                                                       
  	mmr.entered                        entered,                                                        
  	mmr.wo_no                          mmr_wo_no,                                                          
  	mmr.signature                      signature,                                                      
  	mmr.int_destination_desc           int_destination_desc,                                           
  	mmr.contract                       contract,                                                       
  	Site_API.Get_Company(contract) company,                                                        
  	mmr.activity_seq                   activity_seq,                                                   
  	Maint_Material_Requisition_API.Multiple_Mat_Req_Exist(mmr.WO_NO)                                   
        		                       mult_req_line,                                                  
  	mmr.rowid                          maint_mat_requis_objid,                                                           
  	ltrim(lpad(to_char(mmr.rowversion),2000))                    maint_mat_requis_objversion,                           
  	mmr.rowstate                      maint_mat_requis_objstate,                                                        
  	MAINT_MATERIAL_REQUISITION_API.Finite_State_Events__(rowstate)                     maint_mat_requis_objevents,  
  	MAINT_MATERIAL_REQUISITION_API.Finite_State_Decode__(rowstate)                         maint_mat_requis_state,   
  	mrl.line_item_no                   line_item_no,
  	mrl.part_no                        part_no,
  	mrl.spare_contract                 spare_contract,
  	mrl.date_required                  date_required,
  	mrl.plan_qty                       plan_qty,
  	mrl.qty                            qty,
  	mrl.qty_short                      qty_short,
  	mrl.qty_assigned                   qty_assigned,
  	mrl.qty_returned                   qty_returned,
  	nvl(wop.catalog_contract, mrl.catalog_contract)         catalog_contract,
  	nvl(wop.catalog_no, mrl.catalog_no)                     catalog_no,
  	nvl(wop.price_list_no, mrl.price_list_no)               price_list_no,
  	nvl(wop.sales_price, mrl.list_price)                    list_price,
  	wop.sale_unit_price                sale_unit_price,
  	nvl(wop.discount, mrl.discount)    discount,
  	wop.qty_to_invoice                 qty_to_invoice,
  	wop.cost                           cost,
  	mrl.wo_no                          wo_no,
        mrl.plan_line_no                   plan_line_no,
        Active_Work_Order_API.Get_Obj_State(mrl.wo_no) objstate,
        mrl.requisition_no                 requisition_no,
        mrl.line_no                        line_no,
        mrl.release_no                     release_no,
        mrl.serial_no                      serial_no,
        mrl.craft_line_no                  craft_line_no,
        mrl.condition_code                 condition_code,
        Part_Ownership_API.Decode(part_ownership) part_ownership,
        mrl.part_ownership                 part_ownership_db,
        mrl.owner                          owner,
        Maint_Mat_Req_Sup_API.Decode(supply_code) supply_code,
        supply_code                        supply_code_db,
        mrl.job_id                         job_id,
        mrl.std_job_seq                    std_job_seq,
        mrl.rowid                         objid,
        ltrim(lpad(to_char(mrl.rowversion),2000)) objversion
FROM   maint_material_requisition_tab mmr, MAINT_MATERIAL_REQ_LINE_TAB mrl, work_order_planning_tab wop
WHERE  mmr.maint_material_order_no = mrl.maint_material_order_no
AND    mrl.wo_no = wop.wo_no (+)
AND    mrl.plan_line_no = wop.plan_line_no (+)
WITH   read only;