CREATE OR REPLACE VIEW ESI_COUNTING_REPORT AS
SELECT CR.inv_list_no                    inv_list_no,
       CR.contract                       contract,
       CR.second_commodity               second_commodity,
       CR.create_date                    create_date,
       CR.cycle_code                     cycle_code,
       CR.cycle_code_db                  cycle_code_db,
       CR.userid                         userid,
       CR.from_warehouse                 from_warehouse,
       CR.from_bay_no                    from_bay_no,
       CR.to_warehouse                   to_warehouse,
       CR.to_bay_no                      to_bay_no,
       CR.from_part_no                   from_part_no,
       CR.to_part_no                     to_part_no,
       CR.max_qty_onhand                 max_qty_onhand,
       CR.freeze_code                    freeze_code,
       CR.freeze_code_db                 freeze_code_db,
       CR.last_count_date                last_count_date,
       CR.process_count                  process_count,
       CR.include_all_qty                include_all_qty,
       CR.include_all_qty_db             include_all_qty_db,
       CR.exclude_customer_owned         exclude_customer_owned,
       CR.exclude_customer_owned_db      exclude_customer_owned_db,
       CR.exclude_supplier_loaned        exclude_supplier_loaned,
       CR.exclude_supplier_loaned_db     exclude_supplier_loaned_db,
       CR.exclude_consignment            exclude_consignment,
       CR.exclude_consignment_db         exclude_consignment_db,
       CR.exclude_company_owned          exclude_company_owned,
       CR.exclude_company_owned_db       exclude_company_owned_db,
       CR.exclude_rotable_pool           exclude_rotable_pool,
       CR.exclude_rotable_pool_db        exclude_rotable_pool_db,
       CR.exclude_fa_rotable_pool        exclude_fa_rotable_pool,
       CR.exclude_fa_rotable_pool_db     exclude_fa_rotable_pool_db,
       CR.project_id                     project_id,
       CR.exclude_standard_inventory     exclude_standard_inventory,
       CR.exclude_standard_inventory_db  exclude_standard_inventory_db,
       CR.exclude_project_inventory      exclude_project_inventory,
       CR.exclude_project_inventory_db   exclude_project_inventory_db,
       CR.objid                          objid,
       CR.objversion                     objversion,
       CRL.seq                            seq,
       CRL.part_no                        part_no,
       CRL.configuration_id               configuration_id,
       CRL.location_no                    location_no,
       CRL.lot_batch_no                   lot_batch_no,
       CRL.serial_no                      serial_no,
       CRL.eng_chg_level                  eng_chg_level,
       CRL.waiv_dev_rej_no                waiv_dev_rej_no,
       CRL.activity_seq                   activity_seq,
       CRL.project_id                     line_project_id,
       CRL.cost                           cost,
       CRL.last_count_date                line_last_count_date,
       CRL.qty_count1                     qty_count1,
       CRL.qty_onhand                     qty_onhand,
       CRL.catch_qty_counted              catch_qty_counted,
       CRL.catch_qty_onhand               catch_qty_onhand,
       CRL.userid                         line_userid,
       CRL.note_text                      note_text,
       CRL.objid                          line_objid,
       CRL.objversion                     line_objversion
FROM   counting_report CR,
       counting_report_line_nopal CRL
WHERE  CR.inv_list_no = CRL.inv_list_no (+)
  AND  CR.contract = CRL.contract (+)
WITH   read only
