CREATE OR REPLACE VIEW ESI_INVENTORY_PART_IN_STOCK AS
SELECT
       LOC.location_no                   location_no,
       LOC.location_group                location_group,
       LOC.warehouse                     warehouse,
       LOC.bay_no                        bay_no,
       LOC.row_no                        row_no,
       LOC.tier_no                       tier_no,
       LOC.bin_no                        bin_no,
       LOC.location_name                 location_name,
       LOC.priority                      priority,
       LOC.contract                      contract,
       substrb(Inventory_Location_Type_API.Decode(LG.inventory_location_type_db),1,200) location_type,
       LG.inventory_location_type_db     location_type_db,
       ST.part_no                        part_no,
       ST.configuration_id               configuration_id,
       ST.lot_batch_no                   lot_batch_no,
       ST.serial_no                      serial_no,
       ST.eng_chg_level                  eng_chg_level,
       ST.waiv_dev_rej_no                waiv_dev_rej_no,
       ST.activity_seq                   activity_seq,
       ST.avg_unit_transit_cost          avg_unit_transit_cost,
       ST.count_variance                 count_variance,
       ST.expiration_date                expiration_date,
       substrb(Inventory_Part_Freeze_Code_API.Decode(ST.freeze_flag_db),1,200) freeze_flag,
       ST.freeze_flag_db                 freeze_flag_db,
       ST.last_activity_date             last_activity_date,
       ST.last_count_date                last_count_date,
       ST.qty_in_transit                 qty_in_transit,
       ST.qty_onhand                     qty_onhand,
       ST.qty_reserved                   qty_reserved,
       ST.receipt_date                   receipt_date,
       ST.source                         source,
       ST.availability_control_id        availability_control_id,
       ST.condition_code                 condition_code,
       substrb(Part_Ownership_API.Decode(ST.part_ownership_db),1,200) part_ownership,
       ST.part_ownership_db              part_ownership_db,
       ST.owning_vendor_no               owning_vendor_no,
       ST.owning_customer_no             owning_customer_no,
       ST.project_id			 project_id,
       ST.objid                          objid,
       ST.objversion                     objversion
FROM   INVENTORY_PART_IN_STOCK_TOTAL ST,
       INVENTORY_LOCATION LOC,
       INVENTORY_LOCATION_GROUP LG
WHERE  ST.location_no (+) = LOC.location_no
AND    ST.contract (+) = LOC.contract
AND    LG.location_group = LOC.location_group;